name: Step 4, Make a task list

# This step triggers after a commit on the branch `start-markdown`
# This step sets STEP to 5
# This step closes <details id=4> and opens <details id=5>

# This will run every time we create push a commit to `start-markdown`
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - start-markdown

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  on_commit_start_markdown_task_list:
    name: On commit, start markdown, task list

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Let's get all the branches

      # Make sure there is at least one task list item in the file
      - name: Check markdown syntax, task list
        run: ./.github/script/check-file.sh
        env:
          FILE: "index.md"
          SEARCH: "\\- \\[ ] "

      # Update README to close <details id=4> and open <details id=5>
      # and set STEP to '5'
      - name: Update to step 5
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 4
          to_step: 5
          branch_name: start-markdown
